include:
  - template: Docker.gitlab-ci.yml

.pytest_before_script: &pytest_before_script
  - pip install poetry
  - poetry install
  - wget -q https://ai.stanford.edu/\~amaas/data/sentiment/aclImdb_v1.tar.gz -O - | tar -xz -C src/

