include:
  - template: Docker.gitlab-ci.yml

stages:
  - linting
  - test

.linting-template:
  stage: linting
  image: registry.gitlab.com/mafda/python-linting
  before_script:
    - cd src

isort:
  extends: .linting-template
  script:
    - poetry run isort . --check-only

black:
  extends: .linting-template
  script:
    - poetry run black --check .

flake8:
  extends: .linting-template
  script:
    - poetry run flake8 .

pytest:
  stage: test
  before_script:
    - wget -qO- https://ai.stanford.edu/\~amaas/data/sentiment/aclImdb_v1.tar.gz - | tar xvz -C src/
  script:
    - poetry run pytest
