include:
  # - template: Docker.gitlab-ci.yml
    - local: "templates/.ci-include-linting.yml"
stages:
  - linting
  - test

isort:
  extends: .linting-template
  script:
    - isort src --check-only

black:
  extends: .linting-template
  script:
    - black --check src

flake8:
  extends: .linting-template
  script:
    - flake8 src