include:
  - template: Docker.gitlab-ci.yml

stages:
  - linting
  - test
  - build
  - integration

.linting-template:
  stage: linting
  image: python:3.11.5
  before_script:
    - pip install poetry
    - poetry install
    - cd src
  allow_failure: true

isort:
  extends: .linting-template
  script:
    - poetry run isort . --check-only

black:
  extends: .linting-template
  script:
    - poetry run black --check .

flake8:
  extends: .linting-template
  script:
    - poetry run flake8 .

pytest:
  image: python:3.11.5
  stage: test
  before_script:
    - pip install poetry
    - poetry install
    - wget -q https://ai.stanford.edu/\~amaas/data/sentiment/aclImdb_v1.tar.gz -O - | tar -xz -C src/
  script:
    - poetry run pytest

docker-run:
  image: registry.gitlab.com/lewis.marshall2/cicd-excercises
  stage: integration
  script:
    - echo done
