include:
  - template: Docker.gitlab-ci.yml
  - local: templates/.ci-include-linting.yml

stages:
  - linting
  - pytest
  - build
  - integration

.pytest_before_script: &pytest_before_script
  - pip install poetry
  - poetry install
  - wget -q https://ai.stanford.edu/\~amaas/data/sentiment/aclImdb_v1.tar.gz -O - | tar -xz -C src/

isort:
  extends: .linting-template
  script:
    - poetry run isort . --check-only

black:
  extends: .linting-template
  script:
    - poetry run black --check .

flake8:
  extends: .linting-template
  script:
    - poetry run flake8 .

pytest:
  image: python:3.11.5
  stage: pytest
  before_script:
    *pytest_before_script
  script:
    - poetry run pytest

docker-run:
  image: registry.gitlab.com/facultyai/fellowship/mle-fellowship-teaching-resources/ci-cd:$CI_COMMIT_REF_SLUG
  stage: integration
  script:
    - poetry run python3 -m src.main
